Models/ErrorViewModel.cs
namespace pc4_test.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Producto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pc4_test.Models
{
    public class Producto
    {
        public int ProductoId { get; set; }
        public string ProductoNombre { get; set; }
        public bool liked;
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using pc4_test.Models;

namespace pc4_test.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/MLController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.ML;
using pc4_test.DataStructure;
using pc4_test.Services;

namespace pc4_test.Controllers
{
    public class MLController : Controller
    {
        private readonly ILogger<MLController> _logger;
        private readonly PredictionEnginePool<ProductoRating, ProductoRatingPrediction> _model;
        private readonly ProductoService _productoService;
        public MLController(ILogger<MLController> logger,
        PredictionEnginePool<ProductoRating, ProductoRatingPrediction> model,
        ProductoService productoService)
        {
            _logger = logger;
            _model = model;
            _productoService = productoService;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Predict(int id)
        {
            List<(int productoId, float normalizedScore)> ratings = new List<(int productoId, float normalizedScore)>();
            ProductoRatingPrediction prediction = null;

            foreach (var producto in _productoService.getAllProductos())
            {
                // Call the Rating Prediction for each movie prediction
                prediction = _model.Predict(new ProductoRating
                {
                    userid = id,
                    productoid = producto.ProductoId // Asegúrate de que coincide con el nombre de la propiedad en ProductoRating
                });

                // Normalize the prediction scores for the "ratings" b/w 0 - 100
                float normalizedscore = Sigmoid(prediction.Score);

                // Add the score for recommendation of each movie in the trending movie list
                ratings.Add((producto.ProductoId, normalizedscore));
            }

            ratings = ratings.OrderByDescending(r => r.normalizedScore).ToList();

            ViewData["ratings"] = ratings;
            ViewData["productos"] = _productoService.getAllProductos();
            return View("Index");
        }

        public IActionResult Trending()
        {
            return View();
        }
        public IActionResult PredictTrending(int id)
        {
            List<(int productoId, float normalizedScore)> ratings = new List<(int productoId, float normalizedScore)>();
            ProductoRatingPrediction prediction = null;

            foreach (var producto in _productoService.getTrendingProductos())
            {
                // Call the Rating Prediction for each movie prediction
                prediction = _model.Predict(new ProductoRating
                {
                    userid = id,
                    productoid = producto.ProductoId // Asegúrate de que coincide con el nombre de la propiedad en ProductoRating
                });

                // Normalize the prediction scores for the "ratings" b/w 0 - 100
                float normalizedscore = Sigmoid(prediction.Score);

                // Add the score for recommendation of each movie in the trending movie list
                ratings.Add((producto.ProductoId, normalizedscore));
            }

            ratings = ratings.OrderByDescending(r => r.normalizedScore).ToList();

            ViewData["ratings"] = ratings;
            ViewData["trendingproductos"] = _productoService.getTrendingProductos();
            return View("Trending");
        }
        public float Sigmoid(float x)
        {
            return (float) (100/(1 + Math.Exp(-x)));
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/ML/Index.cshtml
@{
    ViewData["Title"] = "Análisis de Recomendaciones";
    var ratings = ViewData["ratings"] as List<(int productoId, float normalizedScore)>;
    var productos = ViewData["productos"] as List<pc4_test.Models.Producto>;
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="ML" asp-action="Predict" method="post">
    <div class="form-group">
        <label for="id">Escribe el Id del usuario</label>
        <input type="text" class="form-control" id="id" name="id" />
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

@if (ratings != null && productos != null)
{
    <h2>Recomendaciones</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Producto</th>
                <th>Puntuación</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var rating in ratings)
            {
                var producto = productos.FirstOrDefault(p => p.ProductoId == rating.productoId);
                if (producto != null)
                {
                    <tr>
                        <td>@producto.ProductoNombre</td>
                        <td>@rating.normalizedScore</td>
                    </tr>
                }
            }
        </tbody>
    </table>
}

Views/ML/Trending.cshtml
@{
    ViewData["Title"] = "Análisis de Recomendaciones";
    var ratings = ViewData["ratings"] as List<(int productoId, float normalizedScore)>;
    var trendingProductos = ViewData["trendingproductos"] as List<pc4_test.Models.Producto>;
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="ML" asp-action="PredictTrending" method="post">
    <div class="form-group">
        <label for="id">Escribe el Id del usuario</label>
        <input type="text" class="form-control" id="id" name="id" />
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

@if (ratings != null && trendingProductos != null)
{
    <h2>Recomendaciones</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Producto</th>
                <th>Puntuación</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var rating in ratings)
            {
                var producto = trendingProductos.FirstOrDefault(p => p.ProductoId == rating.productoId);
                if (producto != null)
                {
                    <tr>
                        <td>@producto.ProductoNombre</td>
                        <td>@rating.normalizedScore</td>
                    </tr>
                }
            }
        </tbody>
    </table>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - pc4_test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/pc4_test.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">pc4_test</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ML" asp-action="Index">Recomendaciones Todos los Platos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ML" asp-action="Trending">Recomendaciones Top 3 Platos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - pc4_test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>